spring:
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/cbot?createDatabaseIfNotExist=true
    username: root
    password: password

tokens:
  file: ${TOKEN_LOCATION:tokens.properties}